--- #YAML:1.0
name:                Data-GUID
version:             0.042
abstract:            globally unique identifiers
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Data::UUID:                    0.13
    Sub::Exporter:                 0.9
    Sub::Install:                  0.03
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo Signes <rjbs@cpan.org>
