--- #YAML:1.0
name:               Data-GUID
version:            0.045
abstract:           globally unique identifiers
author:
    - Ricardo Signes <rjbs@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::UUID:     1.148
    Sub::Exporter:  0.9
    Sub::Install:   0.03
    Test::More:     0
resources:
    Repository:  http://github.com/rjbs/data-guid
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
