# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-GUID
version:      0.01
version_from: lib/Data/GUID.pm
installdirs:  site
requires:
    Data::UUID:                    0.13
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
